### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by sboosali** [sergv/emacs-module#1]
since you link against the GPL-licensed `emacs-module.h`, doesn't the project need to be at least as restrictively licensed too? e.g. something like

    license: GPL-3.0-or-later

in the `.cabal` instead of `BSD3`?

**Comment by ivan-m** [comment]
IANAL, but I think the implication is that the _library code_ is BSD3, but any resulting executable needs to be GPL-3+.

**Comment by sergv** [comment]
@sboosali Well, for one the project doesn't really *link* to `emacs-module.h` - one can link against static libraries, but not header files. The project is really an advanced preprocessor for `emacs-module.h` and is distributed as such. Whether result of preprocessing, i.e. result of linking against this library, has to be GPL-licensed is the question for a lawyer. Than being said, I'm not a lawyer. Perhaps you have some compelling evidence on why the license should be changed?

**Comment by sboosali** [comment]
no compelling reason, no.

**Comment by sergv** [comment]
I think then we can reconsider and reopen the issue later on when new evidence emerges.
